# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backEnd_route.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import universal.public_pb2
import universal.base_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='backEnd_route.proto',
  package='',
  serialized_pb='\n\x13\x62\x61\x63kEnd_route.proto\x1a\x16universal/public.proto\x1a\x14universal/base.proto2H\n\rroute2backEnd\x12\x37\n\x19rpcOtherBackEndLink2route\x12\x0c.base.int32_\x1a\x0c.public.fake2q\n\rbackEnd2route\x12-\n\x10rpcBackEndReport\x12\x0c.base.int32_\x1a\x0b.base.bool_\x12\x31\n\x13rpcHelloIamAbackEnd\x12\x0c.public.fake\x1a\x0c.public.fakeB\x03\x90\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_ROUTE2BACKEND = _descriptor.ServiceDescriptor(
  name='route2backEnd',
  full_name='route2backEnd',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=69,
  serialized_end=141,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcOtherBackEndLink2route',
    full_name='route2backEnd.rpcOtherBackEndLink2route',
    index=0,
    containing_service=None,
    input_type=universal.base_pb2._INT32_,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class route2backEnd(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _ROUTE2BACKEND
class route2backEnd_Stub(route2backEnd):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _ROUTE2BACKEND


_BACKEND2ROUTE = _descriptor.ServiceDescriptor(
  name='backEnd2route',
  full_name='backEnd2route',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=143,
  serialized_end=256,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcBackEndReport',
    full_name='backEnd2route.rpcBackEndReport',
    index=0,
    containing_service=None,
    input_type=universal.base_pb2._INT32_,
    output_type=universal.base_pb2._BOOL_,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcHelloIamAbackEnd',
    full_name='backEnd2route.rpcHelloIamAbackEnd',
    index=1,
    containing_service=None,
    input_type=universal.public_pb2._FAKE,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class backEnd2route(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _BACKEND2ROUTE
class backEnd2route_Stub(backEnd2route):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _BACKEND2ROUTE

# @@protoc_insertion_point(module_scope)
