# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: achv.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import universal.public_pb2
import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='achv.proto',
  package='achv',
  serialized_pb='\n\nachv.proto\x12\x04\x61\x63hv\x1a\x16universal/public.proto\x1a\x0c\x63ommon.proto\"_\n\x07\x61\x63hvMsg\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x0e\n\x06isDone\x18\x02 \x01(\x05\x12\x10\n\x08\x64oneTime\x18\x03 \x01(\x05\x12\x10\n\x08progress\x18\x04 \x01(\x05\x12\x14\n\x0c\x63ondDoneList\x18\x05 \x03(\x05\"0\n\nachvMsgAll\x12\"\n\x0b\x61\x63hvMsgList\x18\x01 \x03(\x0b\x32\r.achv.achvMsg\"*\n\tshareAchv\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x11\n\tchannelId\x18\x02 \x02(\x05\"-\n\rachvHyperlink\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x10\n\x08\x64oneTime\x18\x03 \x01(\x05\x32>\n\rterminal2main\x12-\n\x0crpcAchvShare\x12\x0f.achv.shareAchv\x1a\x0c.public.fake2\xde\x02\n\rmain2terminal\x12,\n\nrpcAchvAll\x12\x10.achv.achvMsgAll\x1a\x0c.public.fake\x12)\n\nrpcAchvAdd\x12\r.achv.achvMsg\x1a\x0c.public.fake\x12-\n\rrpcAchvDelete\x12\x0e.common.int32_\x1a\x0c.public.fake\x12*\n\x0brpcAchvDone\x12\r.achv.achvMsg\x1a\x0c.public.fake\x12\x30\n\x11rpcAchvChangeProg\x12\r.achv.achvMsg\x1a\x0c.public.fake\x12\x30\n\x11rpcAchvChangeCond\x12\r.achv.achvMsg\x1a\x0c.public.fake\x12\x35\n\x10rpcAchvHyperlink\x12\x13.achv.achvHyperlink\x1a\x0c.public.fakeB\x03\x90\x01\x01')




_ACHVMSG = _descriptor.Descriptor(
  name='achvMsg',
  full_name='achv.achvMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='achv.achvMsg.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isDone', full_name='achv.achvMsg.isDone', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doneTime', full_name='achv.achvMsg.doneTime', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='progress', full_name='achv.achvMsg.progress', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='condDoneList', full_name='achv.achvMsg.condDoneList', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=153,
)


_ACHVMSGALL = _descriptor.Descriptor(
  name='achvMsgAll',
  full_name='achv.achvMsgAll',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='achvMsgList', full_name='achv.achvMsgAll.achvMsgList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=155,
  serialized_end=203,
)


_SHAREACHV = _descriptor.Descriptor(
  name='shareAchv',
  full_name='achv.shareAchv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='achv.shareAchv.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channelId', full_name='achv.shareAchv.channelId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=205,
  serialized_end=247,
)


_ACHVHYPERLINK = _descriptor.Descriptor(
  name='achvHyperlink',
  full_name='achv.achvHyperlink',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='achv.achvHyperlink.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='doneTime', full_name='achv.achvHyperlink.doneTime', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=249,
  serialized_end=294,
)

_ACHVMSGALL.fields_by_name['achvMsgList'].message_type = _ACHVMSG
DESCRIPTOR.message_types_by_name['achvMsg'] = _ACHVMSG
DESCRIPTOR.message_types_by_name['achvMsgAll'] = _ACHVMSGALL
DESCRIPTOR.message_types_by_name['shareAchv'] = _SHAREACHV
DESCRIPTOR.message_types_by_name['achvHyperlink'] = _ACHVHYPERLINK

class achvMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACHVMSG

  # @@protoc_insertion_point(class_scope:achv.achvMsg)

class achvMsgAll(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACHVMSGALL

  # @@protoc_insertion_point(class_scope:achv.achvMsgAll)

class shareAchv(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SHAREACHV

  # @@protoc_insertion_point(class_scope:achv.shareAchv)

class achvHyperlink(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACHVHYPERLINK

  # @@protoc_insertion_point(class_scope:achv.achvHyperlink)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_TERMINAL2MAIN = _descriptor.ServiceDescriptor(
  name='terminal2main',
  full_name='achv.terminal2main',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=296,
  serialized_end=358,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcAchvShare',
    full_name='achv.terminal2main.rpcAchvShare',
    index=0,
    containing_service=None,
    input_type=_SHAREACHV,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class terminal2main(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TERMINAL2MAIN
class terminal2main_Stub(terminal2main):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TERMINAL2MAIN


_MAIN2TERMINAL = _descriptor.ServiceDescriptor(
  name='main2terminal',
  full_name='achv.main2terminal',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=361,
  serialized_end=711,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcAchvAll',
    full_name='achv.main2terminal.rpcAchvAll',
    index=0,
    containing_service=None,
    input_type=_ACHVMSGALL,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcAchvAdd',
    full_name='achv.main2terminal.rpcAchvAdd',
    index=1,
    containing_service=None,
    input_type=_ACHVMSG,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcAchvDelete',
    full_name='achv.main2terminal.rpcAchvDelete',
    index=2,
    containing_service=None,
    input_type=common_pb2._INT32_,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcAchvDone',
    full_name='achv.main2terminal.rpcAchvDone',
    index=3,
    containing_service=None,
    input_type=_ACHVMSG,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcAchvChangeProg',
    full_name='achv.main2terminal.rpcAchvChangeProg',
    index=4,
    containing_service=None,
    input_type=_ACHVMSG,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcAchvChangeCond',
    full_name='achv.main2terminal.rpcAchvChangeCond',
    index=5,
    containing_service=None,
    input_type=_ACHVMSG,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcAchvHyperlink',
    full_name='achv.main2terminal.rpcAchvHyperlink',
    index=6,
    containing_service=None,
    input_type=_ACHVHYPERLINK,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class main2terminal(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _MAIN2TERMINAL
class main2terminal_Stub(main2terminal):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _MAIN2TERMINAL

# @@protoc_insertion_point(module_scope)
