# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: act_instance.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import universal.public_pb2
import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='act_instance.proto',
  package='act_instance',
  serialized_pb='\n\x12\x61\x63t_instance.proto\x12\x0c\x61\x63t_instance\x1a\x16universal/public.proto\x1a\x0c\x63ommon.proto2D\n\rterminal2main\x12\x33\n\x13rpcActInstanceEnter\x12\x0e.common.int32_\x1a\x0c.public.fake2\x0f\n\rmain2terminalB\x03\x90\x01\x01')





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_TERMINAL2MAIN = _descriptor.ServiceDescriptor(
  name='terminal2main',
  full_name='act_instance.terminal2main',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=74,
  serialized_end=142,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcActInstanceEnter',
    full_name='act_instance.terminal2main.rpcActInstanceEnter',
    index=0,
    containing_service=None,
    input_type=common_pb2._INT32_,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class terminal2main(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TERMINAL2MAIN
class terminal2main_Stub(terminal2main):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TERMINAL2MAIN


_MAIN2TERMINAL = _descriptor.ServiceDescriptor(
  name='main2terminal',
  full_name='act_instance.main2terminal',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=144,
  serialized_end=159,
  methods=[
])

class main2terminal(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _MAIN2TERMINAL
class main2terminal_Stub(main2terminal):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _MAIN2TERMINAL

# @@protoc_insertion_point(module_scope)
