# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: miniGame.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='miniGame.proto',
  package='miniGame',
  serialized_pb='\n\x0eminiGame.proto\x12\x08miniGame\"D\n\x10startTurnCardMsg\x12\x0f\n\x07iChance\x18\x01 \x02(\x05\x12\r\n\x05sCost\x18\x02 \x02(\x0c\x12\x10\n\x08iTimeout\x18\x03 \x02(\x05')




_STARTTURNCARDMSG = _descriptor.Descriptor(
  name='startTurnCardMsg',
  full_name='miniGame.startTurnCardMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iChance', full_name='miniGame.startTurnCardMsg.iChance', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sCost', full_name='miniGame.startTurnCardMsg.sCost', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iTimeout', full_name='miniGame.startTurnCardMsg.iTimeout', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=28,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['startTurnCardMsg'] = _STARTTURNCARDMSG

class startTurnCardMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _STARTTURNCARDMSG

  # @@protoc_insertion_point(class_scope:miniGame.startTurnCardMsg)


# @@protoc_insertion_point(module_scope)
