# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signIn.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import universal.public_pb2
import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='signIn.proto',
  package='signIn',
  serialized_pb='\n\x0csignIn.proto\x12\x06signIn\x1a\x16universal/public.proto\x1a\x0c\x63ommon.proto\"\x1e\n\nsignInType\x12\x10\n\x08signType\x18\x01 \x02(\r\"S\n\tsignInMsg\x12\x11\n\tsignCount\x18\x01 \x02(\r\x12\x0e\n\x06signIn\x18\x02 \x02(\r\x12\x11\n\tsignAgain\x18\x03 \x02(\r\x12\x10\n\x08signType\x18\x04 \x01(\r2q\n\rterminal2main\x12\x31\n\rrpcSignInOpen\x12\x12.signIn.signInType\x1a\x0c.public.fake\x12-\n\trpcSignIn\x12\x12.signIn.signInType\x1a\x0c.public.fake2@\n\rmain2terminal\x12/\n\x0crpcSignInMsg\x12\x11.signIn.signInMsg\x1a\x0c.public.fakeB\x03\x90\x01\x01')




_SIGNINTYPE = _descriptor.Descriptor(
  name='signInType',
  full_name='signIn.signInType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signType', full_name='signIn.signInType.signType', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=62,
  serialized_end=92,
)


_SIGNINMSG = _descriptor.Descriptor(
  name='signInMsg',
  full_name='signIn.signInMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signCount', full_name='signIn.signInMsg.signCount', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signIn', full_name='signIn.signInMsg.signIn', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signAgain', full_name='signIn.signInMsg.signAgain', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signType', full_name='signIn.signInMsg.signType', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=94,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['signInType'] = _SIGNINTYPE
DESCRIPTOR.message_types_by_name['signInMsg'] = _SIGNINMSG

class signInType(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNINTYPE

  # @@protoc_insertion_point(class_scope:signIn.signInType)

class signInMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIGNINMSG

  # @@protoc_insertion_point(class_scope:signIn.signInMsg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_TERMINAL2MAIN = _descriptor.ServiceDescriptor(
  name='terminal2main',
  full_name='signIn.terminal2main',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=179,
  serialized_end=292,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcSignInOpen',
    full_name='signIn.terminal2main.rpcSignInOpen',
    index=0,
    containing_service=None,
    input_type=_SIGNINTYPE,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcSignIn',
    full_name='signIn.terminal2main.rpcSignIn',
    index=1,
    containing_service=None,
    input_type=_SIGNINTYPE,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class terminal2main(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TERMINAL2MAIN
class terminal2main_Stub(terminal2main):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TERMINAL2MAIN


_MAIN2TERMINAL = _descriptor.ServiceDescriptor(
  name='main2terminal',
  full_name='signIn.main2terminal',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=294,
  serialized_end=358,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcSignInMsg',
    full_name='signIn.main2terminal.rpcSignInMsg',
    index=0,
    containing_service=None,
    input_type=_SIGNINMSG,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class main2terminal(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _MAIN2TERMINAL
class main2terminal_Stub(main2terminal):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _MAIN2TERMINAL

# @@protoc_insertion_point(module_scope)
