# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: title.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import universal.public_pb2
import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='title.proto',
  package='title',
  serialized_pb='\n\x0btitle.proto\x12\x05title\x1a\x16universal/public.proto\x1a\x0c\x63ommon.proto\"H\n\ttitleInfo\x12\x0b\n\x03iNo\x18\x01 \x02(\x05\x12\r\n\x05sName\x18\x02 \x01(\x0c\x12\x0f\n\x07iExpire\x18\x03 \x01(\x05\x12\x0e\n\x06\x62IsNew\x18\x04 \x01(\x08\"D\n\ttitleList\x12\x12\n\niWearTitle\x18\x01 \x01(\x05\x12#\n\ttitleInfo\x18\x02 \x03(\x0b\x32\x10.title.titleInfo\"\x17\n\x06uiInfo\x12\r\n\x05iUINo\x18\x01 \x02(\x05\x32t\n\rterminal2main\x12\x30\n\x0erpcActiveTitle\x12\x10.title.titleInfo\x1a\x0c.public.fake\x12\x31\n\x0frpcAcquireTitle\x12\x10.title.titleInfo\x1a\x0c.public.fake2\x81\x02\n\rmain2terminal\x12-\n\x0brpcAddTitle\x12\x10.title.titleInfo\x1a\x0c.public.fake\x12\x30\n\x0erpcRemoveTitle\x12\x10.title.titleInfo\x1a\x0c.public.fake\x12.\n\x0crpcTitleList\x12\x10.title.titleList\x1a\x0c.public.fake\x12\x30\n\x0erpcTitleUpdate\x12\x10.title.titleList\x1a\x0c.public.fake\x12-\n\x0erpcTitleOpenUI\x12\r.title.uiInfo\x1a\x0c.public.fakeB\x03\x90\x01\x01')




_TITLEINFO = _descriptor.Descriptor(
  name='titleInfo',
  full_name='title.titleInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iNo', full_name='title.titleInfo.iNo', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sName', full_name='title.titleInfo.sName', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iExpire', full_name='title.titleInfo.iExpire', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bIsNew', full_name='title.titleInfo.bIsNew', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=60,
  serialized_end=132,
)


_TITLELIST = _descriptor.Descriptor(
  name='titleList',
  full_name='title.titleList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iWearTitle', full_name='title.titleList.iWearTitle', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='titleInfo', full_name='title.titleList.titleInfo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=134,
  serialized_end=202,
)


_UIINFO = _descriptor.Descriptor(
  name='uiInfo',
  full_name='title.uiInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iUINo', full_name='title.uiInfo.iUINo', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=204,
  serialized_end=227,
)

_TITLELIST.fields_by_name['titleInfo'].message_type = _TITLEINFO
DESCRIPTOR.message_types_by_name['titleInfo'] = _TITLEINFO
DESCRIPTOR.message_types_by_name['titleList'] = _TITLELIST
DESCRIPTOR.message_types_by_name['uiInfo'] = _UIINFO

class titleInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TITLEINFO

  # @@protoc_insertion_point(class_scope:title.titleInfo)

class titleList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TITLELIST

  # @@protoc_insertion_point(class_scope:title.titleList)

class uiInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UIINFO

  # @@protoc_insertion_point(class_scope:title.uiInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_TERMINAL2MAIN = _descriptor.ServiceDescriptor(
  name='terminal2main',
  full_name='title.terminal2main',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=229,
  serialized_end=345,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcActiveTitle',
    full_name='title.terminal2main.rpcActiveTitle',
    index=0,
    containing_service=None,
    input_type=_TITLEINFO,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcAcquireTitle',
    full_name='title.terminal2main.rpcAcquireTitle',
    index=1,
    containing_service=None,
    input_type=_TITLEINFO,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class terminal2main(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TERMINAL2MAIN
class terminal2main_Stub(terminal2main):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TERMINAL2MAIN


_MAIN2TERMINAL = _descriptor.ServiceDescriptor(
  name='main2terminal',
  full_name='title.main2terminal',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=348,
  serialized_end=605,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcAddTitle',
    full_name='title.main2terminal.rpcAddTitle',
    index=0,
    containing_service=None,
    input_type=_TITLEINFO,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcRemoveTitle',
    full_name='title.main2terminal.rpcRemoveTitle',
    index=1,
    containing_service=None,
    input_type=_TITLEINFO,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcTitleList',
    full_name='title.main2terminal.rpcTitleList',
    index=2,
    containing_service=None,
    input_type=_TITLELIST,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcTitleUpdate',
    full_name='title.main2terminal.rpcTitleUpdate',
    index=3,
    containing_service=None,
    input_type=_TITLELIST,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcTitleOpenUI',
    full_name='title.main2terminal.rpcTitleOpenUI',
    index=4,
    containing_service=None,
    input_type=_UIINFO,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class main2terminal(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _MAIN2TERMINAL
class main2terminal_Stub(main2terminal):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _MAIN2TERMINAL

# @@protoc_insertion_point(module_scope)
