# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: words.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import universal.public_pb2
import common_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='words.proto',
  package='words',
  serialized_pb='\n\x0bwords.proto\x12\x05words\x1a\x16universal/public.proto\x1a\x0c\x63ommon.proto\")\n\x07\x63ontent\x12\r\n\x05\x65vent\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"F\n\twordsInfo\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x0e\n\x06\x65ntity\x18\x02 \x02(\x03\x12\x1b\n\x03msg\x18\x03 \x01(\x0b\x32\x0e.words.content\"J\n\twordsList\x12\x0c\n\x04type\x18\x01 \x02(\x05\x12\x0e\n\x06\x65ntity\x18\x02 \x02(\x03\x12\x1f\n\x07msgList\x18\x03 \x03(\x0b\x32\x0e.words.content2\x9e\x01\n\rterminal2main\x12-\n\x0brpcWordsGet\x12\x10.words.wordsInfo\x1a\x0c.public.fake\x12-\n\x0brpcWordsSet\x12\x10.words.wordsInfo\x1a\x0c.public.fake\x12/\n\rrpcWordsReset\x12\x10.words.wordsInfo\x1a\x0c.public.fake2n\n\rmain2terminal\x12.\n\x0crpcWordsList\x12\x10.words.wordsList\x1a\x0c.public.fake\x12-\n\x0brpcWordsMod\x12\x10.words.wordsInfo\x1a\x0c.public.fakeB\x03\x90\x01\x01')




_CONTENT = _descriptor.Descriptor(
  name='content',
  full_name='words.content',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='words.content.event', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='words.content.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=60,
  serialized_end=101,
)


_WORDSINFO = _descriptor.Descriptor(
  name='wordsInfo',
  full_name='words.wordsInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='words.wordsInfo.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity', full_name='words.wordsInfo.entity', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msg', full_name='words.wordsInfo.msg', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=103,
  serialized_end=173,
)


_WORDSLIST = _descriptor.Descriptor(
  name='wordsList',
  full_name='words.wordsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='words.wordsList.type', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity', full_name='words.wordsList.entity', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='msgList', full_name='words.wordsList.msgList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=175,
  serialized_end=249,
)

_WORDSINFO.fields_by_name['msg'].message_type = _CONTENT
_WORDSLIST.fields_by_name['msgList'].message_type = _CONTENT
DESCRIPTOR.message_types_by_name['content'] = _CONTENT
DESCRIPTOR.message_types_by_name['wordsInfo'] = _WORDSINFO
DESCRIPTOR.message_types_by_name['wordsList'] = _WORDSLIST

class content(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTENT

  # @@protoc_insertion_point(class_scope:words.content)

class wordsInfo(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORDSINFO

  # @@protoc_insertion_point(class_scope:words.wordsInfo)

class wordsList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _WORDSLIST

  # @@protoc_insertion_point(class_scope:words.wordsList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\220\001\001')

_TERMINAL2MAIN = _descriptor.ServiceDescriptor(
  name='terminal2main',
  full_name='words.terminal2main',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=252,
  serialized_end=410,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcWordsGet',
    full_name='words.terminal2main.rpcWordsGet',
    index=0,
    containing_service=None,
    input_type=_WORDSINFO,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcWordsSet',
    full_name='words.terminal2main.rpcWordsSet',
    index=1,
    containing_service=None,
    input_type=_WORDSINFO,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcWordsReset',
    full_name='words.terminal2main.rpcWordsReset',
    index=2,
    containing_service=None,
    input_type=_WORDSINFO,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class terminal2main(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _TERMINAL2MAIN
class terminal2main_Stub(terminal2main):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _TERMINAL2MAIN


_MAIN2TERMINAL = _descriptor.ServiceDescriptor(
  name='main2terminal',
  full_name='words.main2terminal',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=412,
  serialized_end=522,
  methods=[
  _descriptor.MethodDescriptor(
    name='rpcWordsList',
    full_name='words.main2terminal.rpcWordsList',
    index=0,
    containing_service=None,
    input_type=_WORDSLIST,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='rpcWordsMod',
    full_name='words.main2terminal.rpcWordsMod',
    index=1,
    containing_service=None,
    input_type=_WORDSINFO,
    output_type=universal.public_pb2._FAKE,
    options=None,
  ),
])

class main2terminal(_service.Service):
  __metaclass__ = service_reflection.GeneratedServiceType
  DESCRIPTOR = _MAIN2TERMINAL
class main2terminal_Stub(main2terminal):
  __metaclass__ = service_reflection.GeneratedServiceStubType
  DESCRIPTOR = _MAIN2TERMINAL

# @@protoc_insertion_point(module_scope)
