# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: backEnd.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='backEnd.proto',
  package='backEnd',
  serialized_pb='\n\rbackEnd.proto\x12\x07\x62\x61\x63kEnd*l\n\x0b\x62\x61\x63kEndType\x12\x13\n\x0fUNKNOWN_SERVICE\x10\x00\x12\x10\n\x0cMAIN_SERVICE\x10\x01\x12\x11\n\rSCENE_SERVICE\x10\x02\x12\x11\n\rFIGHT_SERVICE\x10\x04\x12\x10\n\x0c\x43HAT_SERVICE\x10\x08')

_BACKENDTYPE = _descriptor.EnumDescriptor(
  name='backEndType',
  full_name='backEnd.backEndType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN_SERVICE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MAIN_SERVICE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCENE_SERVICE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FIGHT_SERVICE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAT_SERVICE', index=4, number=8,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=26,
  serialized_end=134,
)

backEndType = enum_type_wrapper.EnumTypeWrapper(_BACKENDTYPE)
UNKNOWN_SERVICE = 0
MAIN_SERVICE = 1
SCENE_SERVICE = 2
FIGHT_SERVICE = 4
CHAT_SERVICE = 8




# @@protoc_insertion_point(module_scope)
