# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: public.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='public.proto',
  package='public',
  serialized_pb='\n\x0cpublic.proto\x12\x06public\"\x06\n\x04\x66\x61ke\"&\n\x04\x66\x61il\x12\x0f\n\x07sReason\x18\x01 \x01(\x0c\x12\r\n\x05iCode\x18\x02 \x01(\x11\"\x94\x01\n\x07request\x12\x12\n\niRequestId\x18\x01 \x01(\x04\x12\x16\n\x0eiPeerRequestId\x18\x02 \x01(\x04\x12\x13\n\x0bsMethodName\x18\x03 \x02(\x0c\x12\x13\n\x0bsSerialized\x18\x04 \x01(\x0c\x12\x0e\n\x06iStamp\x18\x05 \x01(\x03\x12\x10\n\x08iTimeout\x18\x06 \x01(\r\x12\x11\n\tiSequence\x18\x07 \x01(\x04\"j\n\x08response\x12\x13\n\x0biResponseId\x18\x01 \x01(\x04\x12\x34\n\x08iSubType\x18\x02 \x01(\x0e\x32\x14.public.responseType:\x0cTYPE_SUCCESS\x12\x13\n\x0bsSerialized\x18\x03 \x01(\x0c\"a\n\x06packet\x12/\n\x05iType\x18\x01 \x01(\x0e\x32\x12.public.packetType:\x0cTYPE_REQUEST\x12\x13\n\x0bsSerialized\x18\x02 \x02(\x0c\x12\x11\n\tsCheckSum\x18\x03 \x01(\x0c*1\n\npacketType\x12\x10\n\x0cTYPE_REQUEST\x10\x00\x12\x11\n\rTYPE_RESPONSE\x10\x01*/\n\x0cresponseType\x12\x10\n\x0cTYPE_SUCCESS\x10\x00\x12\r\n\tTYPE_FAIL\x10\x01')

_PACKETTYPE = _descriptor.EnumDescriptor(
  name='packetType',
  full_name='public.packetType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_REQUEST', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_RESPONSE', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=430,
  serialized_end=479,
)

packetType = enum_type_wrapper.EnumTypeWrapper(_PACKETTYPE)
_RESPONSETYPE = _descriptor.EnumDescriptor(
  name='responseType',
  full_name='public.responseType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_SUCCESS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_FAIL', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=481,
  serialized_end=528,
)

responseType = enum_type_wrapper.EnumTypeWrapper(_RESPONSETYPE)
TYPE_REQUEST = 0
TYPE_RESPONSE = 1
TYPE_SUCCESS = 0
TYPE_FAIL = 1



_FAKE = _descriptor.Descriptor(
  name='fake',
  full_name='public.fake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=30,
)


_FAIL = _descriptor.Descriptor(
  name='fail',
  full_name='public.fail',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sReason', full_name='public.fail.sReason', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iCode', full_name='public.fail.iCode', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=70,
)


_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='public.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iRequestId', full_name='public.request.iRequestId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iPeerRequestId', full_name='public.request.iPeerRequestId', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sMethodName', full_name='public.request.sMethodName', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sSerialized', full_name='public.request.sSerialized', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iStamp', full_name='public.request.iStamp', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iTimeout', full_name='public.request.iTimeout', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iSequence', full_name='public.request.iSequence', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=73,
  serialized_end=221,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='public.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iResponseId', full_name='public.response.iResponseId', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iSubType', full_name='public.response.iSubType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sSerialized', full_name='public.response.sSerialized', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=223,
  serialized_end=329,
)


_PACKET = _descriptor.Descriptor(
  name='packet',
  full_name='public.packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iType', full_name='public.packet.iType', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sSerialized', full_name='public.packet.sSerialized', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sCheckSum', full_name='public.packet.sCheckSum', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=331,
  serialized_end=428,
)

_RESPONSE.fields_by_name['iSubType'].enum_type = _RESPONSETYPE
_PACKET.fields_by_name['iType'].enum_type = _PACKETTYPE
DESCRIPTOR.message_types_by_name['fake'] = _FAKE
DESCRIPTOR.message_types_by_name['fail'] = _FAIL
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['packet'] = _PACKET

class fake(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FAKE

  # @@protoc_insertion_point(class_scope:public.fake)

class fail(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FAIL

  # @@protoc_insertion_point(class_scope:public.fail)

class request(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST

  # @@protoc_insertion_point(class_scope:public.request)

class response(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSE

  # @@protoc_insertion_point(class_scope:public.response)

class packet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKET

  # @@protoc_insertion_point(class_scope:public.packet)


# @@protoc_insertion_point(module_scope)
